### ISSUE TITLE
Micro USB is working

### ISSUE THREAD

**Issue by javierspn** [willyneutron/lubuntu_in_chuwi_Hi10Pro#1]
Heya!

Micro USB is working. Lubuntu 20.04.

My integrated Wifi chip is unstable so I connected a spare TPLink usb wifi card with a micro USB to USB adapter and it works perfectly.

Tested also with an external USB keyboard and mouse, both working well.

Just a heads up!

Also, I am currently using the tablet as a dockers learning lab and the performance is perfectly fine, much better than either Android or Windows I must say.

**Comment by willyneutron** [comment]
Hi javierspn,

Nice to hear that!

This information will be useful for someone else wanting to upgrade to Ubuntu/Lubuntu.

Thank you!
